#!/usr/bin/env python3
"""
Gmail App Password Generator Guide

This script opens the Gmail App Password generation page in your browser
and provides step-by-step instructions.
"""

import webbrowser
import time
import os

def show_instructions():
    print("=" * 70)
    print("📧 GMAIL APP PASSWORD - STEP BY STEP GUIDE")
    print("=" * 70)
    print()
    print("⚠️  IMPORTANT: You CANNOT use your regular Gmail password!")
    print("   Gmail requires a special 16-character 'App Password'")
    print()
    print("=" * 70)
    print("STEP 1: Enable 2-Factor Authentication")
    print("=" * 70)
    print()
    print("1. I'll open the Google Security page in your browser")
    print("2. Sign in to your Google Account")
    print("3. Find '2-Step Verification'")
    print("4. Click 'Get Started' if not enabled")
    print("5. Follow the instructions to set it up")
    print()
    
    input("Press ENTER to open Google Security page...")
    webbrowser.open("https://myaccount.google.com/security")
    print("✅ Opened: https://myaccount.google.com/security")
    print()
    print("⏳ Please enable 2-Factor Authentication first...")
    print()
    input("Press ENTER when 2FA is enabled and you're ready to continue...")
    
    print()
    print("=" * 70)
    print("STEP 2: Generate App Password")
    print("=" * 70)
    print()
    print("Now I'll open the App Passwords page...")
    print()
    print("Follow these steps:")
    print()
    print("1. You should see 'App passwords' section")
    print("2. Click on 'App passwords'")
    print("3. You may need to sign in again")
    print("4. Under 'Select app', choose: 'Mail'")
    print("5. Under 'Select device', choose: 'Other (Custom name)'")
    print("6. Enter name: 'Django Password Reset'")
    print("7. Click 'Generate'")
    print()
    print("📋 YOU WILL SEE A 16-CHARACTER PASSWORD LIKE:")
    print("   xxxx xxxx xxxx xxxx")
    print()
    print("⚠️  IMPORTANT:")
    print("   - Copy this password immediately")
    print("   - You won't see it again")
    print("   - Write it down or save it")
    print()
    
    input("Press ENTER to open App Passwords page...")
    webbrowser.open("https://myaccount.google.com/apppasswords")
    print("✅ Opened: https://myaccount.google.com/apppasswords")
    print()
    
    print("=" * 70)
    print("STEP 3: Save Your App Password")
    print("=" * 70)
    print()
    print("After generating the App Password:")
    print()
    print("1. Copy the 16-character password (format: xxxx xxxx xxxx xxxx)")
    print("2. Keep this password safe")
    print("3. You'll need to enter it in the next step")
    print()
    
    input("Press ENTER when you have copied the App Password...")
    
    print()
    print("=" * 70)
    print("STEP 4: Configure Django with App Password")
    print("=" * 70)
    print()
    print("Now run the configuration script:")
    print()
    print("   python3 configure_email.py")
    print()
    print("When asked for password, paste the 16-character App Password")
    print("(You can paste even if you don't see characters appearing)")
    print()
    print("=" * 70)
    print()
    print("📌 QUICK REFERENCE:")
    print()
    print("Your Gmail:", os.environ.get('EMAIL_HOST_USER', 'your-email@example.com'))
    print("App Password: [The 16-character code you just generated]")
    print()
    print("After configuration, test with:")
    print("   python3 test_email_sending.py")
    print()
    print("=" * 70)
    print()

def manual_instructions():
    print()
    print("=" * 70)
    print("📖 MANUAL INSTRUCTIONS (If browser didn't open)")
    print("=" * 70)
    print()
    print("Step 1: Enable 2-Factor Authentication")
    print("   URL: https://myaccount.google.com/security")
    print("   1. Sign in to your Google Account")
    print("   2. Find '2-Step Verification'")
    print("   3. Click 'Get Started'")
    print("   4. Follow setup instructions")
    print()
    print("Step 2: Generate App Password")
    print("   URL: https://myaccount.google.com/apppasswords")
    print("   1. Sign in if needed")
    print("   2. Select app: Mail")
    print("   3. Select device: Other (Custom name)")
    print("   4. Enter: Django Password Reset")
    print("   5. Click Generate")
    print("   6. Copy the 16-character password")
    print()
    print("Step 3: Configure Django")
    print("   Run: python3 configure_email.py")
    import os
    print("   Email:", os.environ.get('EMAIL_HOST_USER', 'your-email@example.com'))
    print("   Password: [Your 16-character App Password]")
    print()
    print("Step 4: Test")
    print("   Run: python3 test_email_sending.py")
    print()

if __name__ == '__main__':
    print()
    try:
        show_instructions()
        
        print()
        choice = input("Would you like to see manual instructions? (y/N): ").strip().lower()
        if choice == 'y':
            manual_instructions()
        
        print()
        print("✅ Setup guide complete!")
        print()
        print("Next: python3 configure_email.py")
        print()
        
    except KeyboardInterrupt:
        print()
        print()
        print("❌ Cancelled by user")
        manual_instructions()
