# Generated by Django 4.2.7 on 2025-10-24 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Cover Letter', max_length=200)),
                ('company_name', models.CharField(help_text='Target company name', max_length=200)),
                ('position', models.CharField(help_text='Job position applying for', max_length=200)),
                ('job_description', models.TextField(blank=True, help_text='Job description (optional)')),
                ('content', models.TextField(help_text='AI-generated cover letter content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cover Letter',
                'verbose_name_plural': 'Cover Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
