# Generated by Django 4.2.7 on 2025-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='template',
            field=models.CharField(default='modern', help_text='Resume template used', max_length=50),
        ),
    ]
