# Generated by Django 4.2.7 on 2025-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_generatedresume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('executive', 'Executive'), ('technical', 'Technical')], default='classic', help_text='Template design for PDF generation', max_length=50),
        ),
    ]
