# Generated by Django 4.2.7 on 2025-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_update_site_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Professional'), ('classic', 'Classic Traditional'), ('creative', 'Creative Bold'), ('minimal', 'Minimal Clean'), ('executive', 'Executive Premium'), ('technical', 'Technical Expert')], default='classic', help_text='Template design for PDF generation', max_length=50),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='template',
            field=models.CharField(choices=[('modern', 'Modern Professional'), ('classic', 'Classic Traditional'), ('creative', 'Creative Bold'), ('minimal', 'Minimal Clean'), ('executive', 'Executive Premium'), ('technical', 'Technical Expert')], default='modern', help_text='Resume template used', max_length=50),
        ),
    ]
